module.exports = new Map([
  ["Azlar", {name: "Azlar", limited: false, element: "Fire", stars: 5, rarity: "Legendary"}],
  ["Guardian Kong", {name: "Guardian Kong", limited: true, element: "Fire", stars: 5, rarity: "Legendary"}],
  ["Marjana", {name: "Marjana", limited: false, element: "Fire", stars: 5, rarity: "Legendary"}],
  ["Khagan", {name: "Khagan", limited: false, element: "Fire", stars: 5, rarity: "Legendary"}],
  ["Captain Kestrel", {name: "Captain Kestrel", limited: true, element: "Fire", stars: 5, rarity: "Legendary"}],
  ["Ares", {name: "Ares", limited: true, element: "Fire", stars: 5, rarity: "Legendary"}],
  ["Elena", {name: "Elena", limited: false, element: "Fire", stars: 5, rarity: "Legendary"}],
  ["Natalya", {name: "Natalya", limited: true, element: "Fire", stars: 5, rarity: "Legendary"}],
  ["Gravemaker", {name: "Gravemaker", limited: true, element: "Fire", stars: 5, rarity: "Legendary"}],
  ["Red Hood", {name: "Red Hood", limited: false, element: "Fire", stars: 5, rarity: "Legendary"}],
  ["Master Lepus", {name: "Master Lepus", limited: false, element: "Ice", stars: 5, rarity: "Legendary"}],
  ["Perseus", {name: "Perseus", limited: true, element: "Ice", stars: 5, rarity: "Legendary"}],
  ["Isarnia", {name: "Isarnia", limited: false, element: "Ice", stars: 5, rarity: "Legendary"}],
  ["Magni", {name: "Magni", limited: false, element: "Ice", stars: 5, rarity: "Legendary"}],
  ["Athena", {name: "Athena", limited: true, element: "Ice", stars: 5, rarity: "Legendary"}],
  ["Thorne", {name: "Thorne", limited: false, element: "Ice", stars: 5, rarity: "Legendary"}],
  ["Richard", {name: "Richard", limited: false, element: "Ice", stars: 5, rarity: "Legendary"}],
  ["King Arthur", {name: "King Arthur", limited: true, element: "Ice", stars: 5, rarity: "Legendary"}],
  ["Alasie", {name: "Alasie", limited: true, element: "Ice", stars: 5, rarity: "Legendary"}],
  ["Rumpelstiltskin", {name: "Rumpelstiltskin", limited: true, element: "Ice", stars: 5, rarity: "Legendary"}],
  ["Kadilen", {name: "Kadilen", limited: false, element: "Nature", stars: 5, rarity: "Legendary"}],
  ["Alberich", {name: "Alberich", limited: true, element: "Nature", stars: 5, rarity: "Legendary"}],
  ["Elkanen", {name: "Elkanen", limited: false, element: "Nature", stars: 5, rarity: "Legendary"}],
  ["Lady Locke", {name: "Lady Locke", limited: true, element: "Nature", stars: 5, rarity: "Legendary"}],
  ["Horghall", {name: "Horghall", limited: false, element: "Nature", stars: 5, rarity: "Legendary"}],
  ["Lianna", {name: "Lianna", limited: false, element: "Nature", stars: 5, rarity: "Legendary"}],
  ["Morgan Le Fay", {name: "Morgan Le Fay", limited: true, element: "Nature", stars: 5, rarity: "Legendary"}],
  ["Zeline", {name: "Zeline", limited: true, element: "Nature", stars: 5, rarity: "Legendary"}],
  ["Yunan", {name: "Yunan", limited: true, element: "Nature", stars: 5, rarity: "Legendary"}],
  ["Gregorion", {name: "Gregorion", limited: true, element: "Nature", stars: 5, rarity: "Legendary"}],
  ["Thoth-Amun", {name: "Thoth-Amun", limited: true, element: "Dark", stars: 5, rarity: "Legendary"}],
  ["Captain Sargasso", {name: "Captain Sargasso", limited: true, element: "Dark", stars: 5, rarity: "Legendary"}],
  ["Hel", {name: "Hel", limited: true, element: "Dark", stars: 5, rarity: "Legendary"}],
  ["Domitia", {name: "Domitia", limited: false, element: "Dark", stars: 5, rarity: "Legendary"}],
  ["Obakan", {name: "Obakan", limited: false, element: "Dark", stars: 5, rarity: "Legendary"}],
  ["Quintus", {name: "Quintus", limited: false, element: "Dark", stars: 5, rarity: "Legendary"}],
  ["Guardian Panther", {name: "Guardian Panther", limited: true, element: "Dark", stars: 5, rarity: "Legendary"}],
  ["Sartana", {name: "Sartana", limited: false, element: "Dark", stars: 5, rarity: "Legendary"}],
  ["Aeron", {name: "Aeron", limited: true, element: "Dark", stars: 5, rarity: "Legendary"}],
  ["Boss Wolf", {name: "Boss Wolf", limited: true, element: "Dark", stars: 5, rarity: "Legendary"}],
  ["Vivica", {name: "Vivica", limited: false, element: "Holy", stars: 5, rarity: "Legendary"}],
  ["Guardian Owl", {name: "Guardian Owl", limited: true, element: "Holy", stars: 5, rarity: "Legendary"}],
  ["Musashi", {name: "Musashi", limited: true, element: "Holy", stars: 5, rarity: "Legendary"}],
  ["Joon", {name: "Joon", limited: false, element: "Holy", stars: 5, rarity: "Legendary"}],
  ["Justice", {name: "Justice", limited: false, element: "Holy", stars: 5, rarity: "Legendary"}],
  ["Leonidas", {name: "Leonidas", limited: false, element: "Holy", stars: 5, rarity: "Legendary"}],
  ["Guinevere", {name: "Guinevere", limited: true, element: "Holy", stars: 5, rarity: "Legendary"}],
  ["Delilah", {name: "Delilah", limited: true, element: "Holy", stars: 5, rarity: "Legendary"}],
  ["Rana", {name: "Rana", limited: true, element: "Holy", stars: 5, rarity: "Legendary"}],
  ["Colen", {name: "Colen", limited: false, element: "Fire", stars: 4, rarity: "Epic"}],
  ["Kelile", {name: "Kelile", limited: false, element: "Fire", stars: 4, rarity: "Epic"}],
  ["Guardian Falcon", {name: "Guardian Falcon", limited: true, element: "Fire", stars: 4, rarity: "Epic"}],
  ["Boldtusk", {name: "Boldtusk", limited: false, element: "Fire", stars: 4, rarity: "Epic"}],
  ["Gormek", {name: "Gormek", limited: false, element: "Fire", stars: 4, rarity: "Epic"}],
  ["Scarlett", {name: "Scarlett", limited: false, element: "Fire", stars: 4, rarity: "Epic"}],
  ["Lancelot", {name: "Lancelot", limited: true, element: "Fire", stars: 4, rarity: "Epic"}],
  ["Kiril", {name: "Kiril", limited: false, element: "Ice", stars: 4, rarity: "Epic"}],
  ["Boril", {name: "Boril", limited: false, element: "Ice", stars: 4, rarity: "Epic"}],
  ["Sonya", {name: "Sonya", limited: false, element: "Ice", stars: 4, rarity: "Epic"}],
  ["Grimm", {name: "Grimm", limited: false, element: "Ice", stars: 4, rarity: "Epic"}],
  ["Jack O'Hare", {name: "Jack O'Hare", limited: true, element: "Nature", stars: 4, rarity: "Epic"}],
  ["Kashhrek", {name: "Kashhrek", limited: false, element: "Nature", stars: 4, rarity: "Epic"}],
  ["Cabin Boy Peters", {name: "Cabin Boy Peters", limited: true, element: "Nature", stars: 4, rarity: "Epic"}],
  ["Little John", {name: "Little John", limited: false, element: "Nature", stars: 4, rarity: "Epic"}],
  ["Caedmon", {name: "Caedmon", limited: false, element: "Nature", stars: 4, rarity: "Epic"}],
  ["Skittleskull", {name: "Skittleskull", limited: false, element: "Nature", stars: 4, rarity: "Epic"}],
  ["Melendor", {name: "Melendor", limited: false, element: "Nature", stars: 4, rarity: "Epic"}],
  ["Hansel", {name: "Hansel", limited: true, element: "Nature", stars: 4, rarity: "Epic"}],
  ["Wu Kong", {name: "Wu Kong", limited: false, element: "Holy", stars: 4, rarity: "Epic"}],
  ["Guardian Jackal", {name: "Guardian Jackal", limited: true, element: "Holy", stars: 4, rarity: "Epic"}],
  ["Li Xiu", {name: "Li Xiu", limited: false, element: "Holy", stars: 4, rarity: "Epic"}],
  ["Chao", {name: "Chao", limited: false, element: "Holy", stars: 4, rarity: "Epic"}],
  ["Hu Tao", {name: "Hu Tao", limited: false, element: "Holy", stars: 4, rarity: "Epic"}],
  ["Gretel", {name: "Gretel", limited: true, element: "Holy", stars: 4, rarity: "Epic"}],
  ["Cyprian", {name: "Cyprian", limited: false, element: "Dark", stars: 4, rarity: "Epic"}],
  ["First Mate Boomer", {name: "First Mate Boomer", limited: false, element: "Dark", stars: 4, rarity: "Epic"}],
  ["Tiburtus", {name: "Tiburtus", limited: false, element: "Dark", stars: 4, rarity: "Epic"}],
  ["Rigard", {name: "Rigard", limited: false, element: "Dark", stars: 4, rarity: "Epic"}],
  ["Sabina", {name: "Sabina", limited: false, element: "Dark", stars: 4, rarity: "Epic"}],
  ["Merlin", {name: "Merlin", limited: false, element: "Dark", stars: 4, rarity: "Epic"}],
  ["Jabbar", {name: "Jabbar", limited: false, element: "Dark", stars: 4, rarity: "Epic"}],
  ["Gaffar", {name: "Gaffar", limited: false, element: "Dark", stars: 4, rarity: "Epic"}],
  ["Azar", {name: "Azar", limited: false, element: "Fire", stars: 3, rarity: "Rare"}],
  ["Hawkmoon", {name: "Hawkmoon", limited: false, element: "Fire", stars: 3, rarity: "Rare"}],
  ["Jahangir", {name: "Jahangir", limited: false, element: "Fire", stars: 3, rarity: "Rare"}],
  ["Nashgar", {name: "Nashgar", limited: false, element: "Fire", stars: 3, rarity: "Rare"}],
  ["Squire Wabbit", {name: "Squire Wabbit", limited: true, element: "Fire", stars: 3, rarity: "Rare"}],
  ["Greymane", {name: "Greymane", limited: false, element: "Ice", stars: 3, rarity: "Rare"}],
  ["Gunnar", {name: "Gunnar", limited: false, element: "Ice", stars: 3, rarity: "Rare"}],
  ["Karil", {name: "Karil", limited: false, element: "Ice", stars: 3, rarity: "Rare"}],
  ["Ulmer", {name: "Ulmer", limited: false, element: "Ice", stars: 3, rarity: "Rare"}],
  ["Valen", {name: "Valen", limited: false, element: "Ice", stars: 3, rarity: "Rare"}],
  ["Belith", {name: "Belith", limited: false, element: "Nature", stars: 3, rarity: "Rare"}],
  ["Berden", {name: "Berden", limited: false, element: "Nature", stars: 3, rarity: "Rare"}],
  ["Brienne", {name: "Brienne", limited: false, element: "Nature", stars: 3, rarity: "Rare"}],
  ["Carver", {name: "Carver", limited: false, element: "Nature", stars: 3, rarity: "Rare"}],
  ["Friar Tuck", {name: "Friar Tuck", limited: false, element: "Nature", stars: 3, rarity: "Rare"}],
  ["Isshtak", {name: "Isshtak", limited: false, element: "Nature", stars: 3, rarity: "Rare"}],
  ["Hisan", {name: "Hisan", limited: true, element: "Nature", stars: 3, rarity: "Rare"}],
  ["Bane", {name: "Bane", limited: false, element: "Holy", stars: 3, rarity: "Rare"}],
  ["Dawa", {name: "Dawa", limited: false, element: "Holy", stars: 3, rarity: "Rare"}],
  ["Gan Ju", {name: "Gan Ju", limited: false, element: "Holy", stars: 3, rarity: "Rare"}],
  ["Kailani", {name: "Kailani", limited: false, element: "Holy", stars: 3, rarity: "Rare"}],
  ["Arman", {name: "Arman", limited: true, element: "Holy", stars: 3, rarity: "Rare"}],
  ["Balthazar", {name: "Balthazar", limited: false, element: "Dark", stars: 3, rarity: "Rare"}],
  ["Tyrum", {name: "Tyrum", limited: false, element: "Dark", stars: 3, rarity: "Rare"}],
  ["Renfeld", {name: "Renfeld", limited: false, element: "Dark", stars: 3, rarity: "Rare"}],
  ["Oberon", {name: "Oberon", limited: false, element: "Dark", stars: 3, rarity: "Rare"}],
  ["Prisca", {name: "Prisca", limited: false, element: "Dark", stars: 3, rarity: "Rare"}],
])
